name: musaab_adam
description: "Musaab Adam Mobile Application - UI Verse."

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  get: ^4.7.2
  flutter_svg: ^2.2.2
  flutter_gen_runner: ^5.12.0
  google_fonts: ^6.3.2
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.10.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf

flutter_gen:
  output: lib/utils/assets_gen


flutter_native_splash:

  color: "#FFFFFF"  ##====================================[REQUIRED]==========
  image: assets/images/splash_logo1024.png
  fullscreen: true                # default false
  android_12:
    # background color
    color: "#FFFFFF"
    image: assets/images/splash_logo1024.png
    # center-logo background color
    icon_background_color: "#FFFFFF"

  #    - family: Momo
  #      fonts:
  #        - asset: fonts/MomoSignature-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700